name: Code Quality

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  lint:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install development dependencies
        run: make install-dev

      - name: Run linting checks
        run: make lint

      - name: Check if code is properly formatted
        run: |
          # This will fail if any files need formatting
          .venv/bin/python -m black --check --diff .
